version: "3"
services:
    amprobe:
        image: amuluze/amprobe:v1.2
        container_name: amprobe # 容器名为'postgresql'
        restart: always
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
            - /dev:/host/dev:ro
            - /etc:/host/etc:ro
            - /:/rootfs:ro
            - /data/amprobe/configs:/app/configs
            - /data/amprobe/nginx/nginx.conf:/etc/nginx/nginx.conf
            - /data/amprobe/supervisor:/etc/supervisor/conf.d
            - /data/amprobe/dist:/usr/share/nginx/html
        ports:
            - 8082:8082
